config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  #get 'users/new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about',to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
						format: { with: VALID_EMAIL_REGEX },
						uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	
	# Returns a random token.
	def self.new_token
		SecureRandom.urlsafe_base64
	end
	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated?(remember_token)
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
	def hello
		render html: "hello, world!"
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
		log_in user
		redirect_to user
	else
		flash.now[:danger] = 'Invalid email/password combination'
		render 'new'
	end
  end
  def destroy
  	log_out
	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# require 'youtube-dl'
class StaticPagesController < ApplicationController
  def home 
  end

  def help
  end

  def download_video
  end
  def download
  	url = "https://www.youtube.com/watch?v=rUWxSEwctFU"
  	
  	Test.download_video(url)
		redirect_to static_pages_home_path
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_user,     only: :destroy

	def index
		@users = User.paginate(page: params[:page])
	end

    def new
	    @user = User.new
	end

	def show
	    @user = User.find(params[:id])
	end

	def create
		#byebug
		@user = User.new(user_params)
		@user.save
		if @user.save
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else 
			render "new"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to users_url
	end
	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = "Please log in first"
			redirect_to login_url
		end
	end
	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns true if the given user is the current user.
	def current_user?(user)
		user == current_user
	end

	# Returns the user corresponding to the remember token cookie.
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	# Redirects to stored location (or to the default).
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	# Stores the URL trying to be accessed.
	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
	
	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for(user, size: 80)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About",'#contact_path' %></li>
<li><%= link_to "Contact", 'contact_path' %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "My App", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "About",about_path %></li>
				<li><%= link_to "Contact Us",contact_path %></li>
				<li><%= link_to "Users", users_path %></li>
				<% if logged_in? %>
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: :delete %>
							</li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_rails-default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <%= render 'layouts/rails-default' %>
     <%= render 'layouts/shim' %>
  </head>

  <body>
<div class="container">
  <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>



<div class="container">


<div class="row">
  <div class="col-sm-6">
  	<img class="card-img-top" src="mydp" alt="Card image cap">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/download_video.html.erb
<% provide(:title, "Download Video") %>
<div class="container">
	<%= button_to "Download Video", static_pages_download_path, method: :get %>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>



<div class="container">

<div class="row">
  <div class="col-sm-6">
  	<img class="card-img-top" src="mydp" alt="Card image cap">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
    <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>
<div class="row">
    <div class="col-sm-4">
       <div class="thumbnail">
        <%= link_to image_tag("mydp.jpg", alt: "Rails logo", style: "width:400px"),
        'http://rubyonrails.org/' %>
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
      </div>
    </div>
  </div>


<!-- <div class="container">


  <div class="row">
    <div class="col-sm-4">
       <div class="thumbnail">
        <img src="<%= asset_path('mydp.jpg') %>" alt="Lights" style="width:100%">
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
    </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="<%= asset_path('mydp.jpg') %>" alt="Lights" style="width:100%">
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
    </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="<%= asset_path('mydp.jpg') %>" alt="Lights" style="width:100%">
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
    </div>
    </div>
  </div>
  <h2 class="text-center"> Table</h2>
  <div class="table-responsive">
  <table class="table table-striped">
  <tr>
    <td>John</td>
    <td>Doe</td>
    <td>john@example.com</td>
  <tr>
  <tr>
    <td>Mary</td>
    <td>Moe</td>
    <td>mary@example.com</td>
  </tr>
  <tr>
    <td>July</td>
    <td>Dooley</td>
    <td>july@example.com</td>
  </tr>
<table>
</div>
<h2 class="text-center"> Badges and list groups</h2>
<ul class="list-group">
  <li class="list-group-item">New <span class="badge">12</span></li>
  <li class="list-group-item">Deleted <span class="badge">5</span></li>
  <li class="list-group-item">Warnings <span class="badge">3</span></li>
</ul>

<h2 class="text-center"> Forms</h2>
<form >
  <div class="form-group">
    <label for="email">Email address:</label>
    <input type="email" class="form-control" id="email">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div> -->

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete,
		data: { confirm: "You sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>
		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>
		<%= f.submit "Save changes", class: "btn btn-primary" %>
	<% end %>
<div class="gravatar_edit">
<%= gravatar_for @user %>
<a href="http://gravatar.com/emails" target="_blank">change</a>
</div>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
	<% @users.each do |user| %>
		<%= render user%>
	<% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, url: signup_path) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
				<%= @user.email %>
			</h1>
		</section>
	</aside>
</div>